### ISSUE TITLE
[error] ObserverCallBack: jython init: we have problems

### ISSUE THREAD

**Issue by Tset-Noitamotua** [Tset-Noitamotua/Sikuli-and-Robot-Framework-Integration#10]
I´m trying to implement an observer keyword which will enable to look for unexpected popups or dialogs during test execution and handle them appropriately.

The following script (observer.py in folder observer.sikuli) works fine from Sikuli IDE and from cmd.
From cmd I call it with `runsikulix.bat -r observer.sikuli`.

``` python
from sikuli import *

region = Region.create(Screen(0).x, Screen(0).y, Screen(0).w, Screen(0).h)
region = Region(region)
region.highlight(2)

def event_handler(event):
    print 'Entered event_handler.'
    # handle popup / dialog ... close, submit, etc. 
    region.stopObserver()
    print 'Observer stopped!'
    return

def event_observer():
    print 'Register Event Observer.'
    region.onAppear(r'C:\path_to_image\image_of_dialog.png', event_handler)
    print 'Registered Event Observer.'

    region.observe(background=True)
    print 'Started Observer.'
    print "wait 10 s"
    wait(10)
    return

event_observer()
```

When I call it with `jython observer.sikuli/observer.py` I get the 'ObserverCallBack error':

![image](https://cloud.githubusercontent.com/assets/5635462/6332051/5538e63e-bb83-11e4-90cd-c5afc0377d59.png)

The same error appears also when calling the 'event_observer()' function from Robot Framework:

![image](https://cloud.githubusercontent.com/assets/5635462/6332390/44257608-bb85-11e4-870f-3cd7c4475316.png)

Am I doing something wrong here? How can I solve that?

**Comment by RaiMan** [comment]
No, everything is according to the usage rules.

I have to check, what happens here.

Until fixed (might only be with the final 1.1.0), to simulate pure Jython usage:

java -cp <path-to-sikulix.jar> org.python.util.jython <path-to>\observer.sikuli/observer.py

**Comment by RaiMan** [comment]
BTW: I guess, you have sikulixapi.jar on the class path in this Jython usage case ???

**Comment by Tset-Noitamotua** [comment]
``` cmd
C:\SikuliX_POC\ecliso\step_3>jython
Jython 2.7b3 (default:e81256215fb0, Aug 4 2014, 02:39:51)
[Java HotSpot(TM) Client VM (Oracle Corporation)] on java1.8.0_05
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print sys.path
['', 'C:\\SikuliX_110\\sikulixapi.jar\\Lib', 'C:\\jython2.7b3\\Lib', '__classpat
h__', '__pyclasspath__/', 'C:\\jython2.7b3\\Lib\\site-packages']
>>>
```

Does this mean that sikulixapi.jar is on the classpath?

**Comment by Tset-Noitamotua** [comment]
I also have a JYTHONPATH environment variable:

``` cmd
C:\SikuliX_POC\ecliso\step_3>echo %jythonpath%
C:\SikuliX_110\sikulixapi.jar\Lib
```

And my SikuliX install folder is on path:
![image](https://cloud.githubusercontent.com/assets/5635462/6347750/aa3aff04-bc1a-11e4-9682-9f8da0b0f197.png)

**Comment by Tset-Noitamotua** [comment]
When I run `java -cp org.python.util.jython \observer.sikuli/observer.py` I get a 'main class not found' error:

``` cmd
C:\SikuliX_POC\ecliso\step_3>java -cp org.python.util.jython \observer.sikuli/observer.py
Fehler: Hauptklasse \observer.sikuli.observer.py konnte nicht gefunden oder geladen werden
```

**Comment by RaiMan** [comment]
uuups, some bullshit ...

the "jython simulation":

if you have a CLASSPATH environment variable, then this should contain 
#path-to#\sikulix.jar (and no sikulixapi.jar and no pointer to the jython.jar)
in the first place and then use:
java org.python.util.jython #path-to#\observer.sikuli\observer.py

if you do not have a CLASSPATH environment variable:
java -cp #path-to#sikulix.jar org.python.util.jython #path-to#\observer.sikuli\observer.py

**Comment by RaiMan** [comment]
BTW: the ObserverCallBack problem will be fixed during the next days (next nightly)

**Comment by Tset-Noitamotua** [comment]
Great to hear. Thanx! I will check it out then and report back here.

**Comment by RaiMan** [comment]
There are available on my Dropbox
sikulix.jar (incl. Jython)
sikulixapi.jar

both already setup for Windows and hence ready to use:
https://dl.dropboxusercontent.com/u/42895525/SikuliX-1.1/sikulixapi.jar
https://dl.dropboxusercontent.com/u/42895525/SikuliX-1.1/sikulix.jar

I have fixed the observe and Debug callback handling, so it can now be used in the context with sikulixapi.jar and external Jython (as you need it for your project) as well.

Take care: the provided jars are ready to use! save the current jars you have! Do not run setup with these jars!

**Comment by Tset-Noitamotua** [comment]
Fantastic! Thanx a lot!

It now works when starting from cmd with `jython observer.sikuli\observer.py`

It also works from Robot Framework when I put the above code at the top of Mike´s 'calc.py' script - so that it is NOT inside the Calculator class - and start it with the robottest.bat script.

BUT (and I hope it´s because of my poor python skills) when I put the code INSIDE the Calculator class I get the exception 'Exception in thread "Thread-4" java.lang.ClassCastException: Cannot cast org.python.core.PyMethod to org.python.core.PyFunction'

My code inside the class looks like this:

``` python
class Calculator(BaseLogger):
    ROBOT_LIBRARY_SCOPE = 'TEST SUITE'

    def __init__(self, *args, **kwargs):
        # ... some more stuff here
        self.region = Region.create(Screen(0).x, Screen(0).y, Screen(0).w, Screen(0).h)
        self.region = Region(self.region)
        self.region.highlight(2)

    def event_handler(self, event):
        print 'Entered event_handler.'
        popup('WARNING! A **** UP PICTURE APPEARED!')
        self.region.stopObserver()
        popup('COOL! Event stopped successfully!')

    def event_observer(self):
        print 'Register Event Observer.'
        self.region.onAppear('image.png', self.event_handler)
        print 'Registered Event Observer.'

        self.region.observe(background=True)
        print 'Started Observer.'
        print "wait 10 s"
        s.wait(10)
```

The full error text:

``` cmd
Exception in thread "Thread-4" java.lang.ClassCastException: Cannot cast org.python.core.PyMethod to org.python.core.PyFunction
    at java.lang.Class.cast(Unknown Source)
    at org.sikuli.util.JythonHelper$PyFunction.<init>(JythonHelper.java:143)
    at org.sikuli.util.JythonHelper.runObserveCallback(JythonHelper.java:235)
    at org.sikuli.script.ObserverCallBack.run(ObserverCallBack.java:97)
    at org.sikuli.script.ObserverCallBack.appeared(ObserverCallBack.java:71)
    at org.sikuli.script.Observer.callEventObserver(Observer.java:162)
    at org.sikuli.script.Observer.checkPatterns(Observer.java:255)
    at org.sikuli.script.Observer.update(Observer.java:396)
    at org.sikuli.script.Region.observeDo(Region.java:3049)
    at org.sikuli.script.Region.observeJ(Region.java:3021)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
    at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
    at org.python.core.PyObject.__call__(PyObject.java:422)
    at org.python.core.PyObject.__call__(PyObject.java:426)
    at org.python.core.PyMethod.__call__(PyMethod.java:139)
    at sikuli.Region$py.observe$6(C:\SikuliX_110\sikulixapi.jar\Lib\sikuli\Region.py:65)
    at sikuli.Region$py.call_function(C:\SikuliX_110\sikulixapi.jar\Lib\sikuli\Region.py)
    at org.python.core.PyTableCode.call(PyTableCode.java:165)
    at org.python.core.PyBaseCode.call(PyBaseCode.java:301)
    at org.python.core.PyBaseCode.call(PyBaseCode.java:194)
    at org.python.core.PyFunction.__call__(PyFunction.java:387)
    at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:220)
    at org.python.core.PyMethod.__call__(PyMethod.java:211)
    at org.python.core.PyMethod.__call__(PyMethod.java:201)
    at org.python.core.PyMethod.__call__(PyMethod.java:196)
    at org.python.core.PyObject._jcallexc(PyObject.java:3502)
    at org.python.core.PyObject._jcall(PyObject.java:3534)
    at org.python.proxies.sikuli.Region$Region$3.observe(Unknown Source)
    at org.sikuli.script.Region$ObserverThread.run(Region.java:3104)
    at java.lang.Thread.run(Unknown Source)
```

Any idea on that?

**Comment by RaiMan** [comment]
Any idea? yes, of course.
Good finding - Thanks for testing.
All this is inside made by reflection and there is obviously a difference between a PyFunction and a PyMethod. I will check and fix that.

**Comment by RaiMan** [comment]
I have fixed the issue: callbacks can now be:
- module functions (including in **main**)
- lambdas
- instance methods 

You might try with the new uploaded sikulixapi.jar

**Comment by Tset-Noitamotua** [comment]
Works nice! Thanx a lot again!!!

**Comment by RaiMan** [comment]
It is a pleasure to support your efforts about using RobotFrameWork with Sikuli.
Please 
give me a note, when ready.

**Comment by Tset-Noitamotua** [comment]
I promise to keep you up to date and I´m sure I will have some more questions before I come even close to 'ready' ;-)
